# Generated by Django 2.2.10 on 2020-04-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200426_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='courseCode',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='takensubject',
            old_name='final_exam',
            new_name='final',
        ),
        migrations.RemoveField(
            model_name='attendancestudent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='takensubject',
            name='mark_data',
        ),
        migrations.AlterField(
            model_name='attendancestudent',
            name='attendance',
            field=models.CharField(choices=[('P', 'PARTICIPATE'), ('NP', 'NOTPARTICIPATE')], default='P', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancestudent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=20),
        ),
        migrations.AlterField(
            model_name='takensubject',
            name='status',
            field=models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=200),
        ),
        migrations.AlterField(
            model_name='takensubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
        ),
    ]
