# Generated by Django 2.2.10 on 2020-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestudent',
            name='faculty',
            field=models.CharField(blank=True, choices=[('FIT', 'FIT'), ('BIS', 'BIS'), ('ISE', 'ISE'), ('MKA', 'MKA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profileteacher',
            name='position',
            field=models.CharField(blank=True, choices=[('LECTOR', 'LECTOR'), ('TUTOR', 'TUTOR'), ('PROFESSOR', 'PROFESSOR'), ('ASSISTANT', 'ASSISTANT')], max_length=50),
        ),
    ]
